#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Write the canonical example reports into the docs.

Usage:
    python scripts/gen_samples.py          # rewrite the docs in place
    python scripts/gen_samples.py --check  # exit 1 if any block is out of date

Each example lives between a pair of HTML comments, which GitHub hides:

    <!-- BEGIN GENERATED: diff-terminal -->
    ```text
    ...
    ```
    <!-- END GENERATED: diff-terminal -->

`--check` is what `tests/test_samples.py` enforces, so a change to a renderer
fails the suite until the docs are regenerated rather than leaving them wrong.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import samples  # noqa: E402  (needs the path insert above)

ROOT = Path(__file__).resolve().parent.parent
TARGETS = ["README.md", "docs/usage.md", "docs/explained.md"]

BEGIN = "<!-- BEGIN GENERATED: {name} -->"
END = "<!-- END GENERATED: {name} -->"


def _block(name: str) -> str:
    body = samples.render(name)
    lang = samples.fence(name)
    rendered = f"```{lang}\n{body}\n```" if lang else body
    return (
        f"{BEGIN.format(name=name)}\n"
        f"<!-- Generated by scripts/gen_samples.py from the real renderers. "
        f"Do not edit by hand. -->\n"
        f"{rendered}\n"
        f"{END.format(name=name)}"
    )


def _pattern(name: str) -> re.Pattern[str]:
    return re.compile(
        re.escape(BEGIN.format(name=name)) + r".*?" + re.escape(END.format(name=name)),
        re.DOTALL,
    )


def process(*, check: bool) -> int:
    stale: list[str] = []
    missing: list[str] = []
    for rel in TARGETS:
        path = ROOT / rel
        text = original = path.read_text("utf-8")
        for name in samples.SAMPLES:
            pattern = _pattern(name)
            if not pattern.search(text):
                continue  # this doc does not use this sample
            replacement = _block(name)
            if pattern.search(text).group(0) != replacement:
                stale.append(f"{rel}:{name}")
            text = pattern.sub(lambda _m, r=replacement: r, text, count=1)
        if text != original and not check:
            path.write_text(text, "utf-8")

    # every sample must actually be used somewhere, or it is dead weight nobody reads
    combined = "\n".join((ROOT / rel).read_text("utf-8") for rel in TARGETS)
    for name in samples.SAMPLES:
        if BEGIN.format(name=name) not in combined:
            missing.append(name)

    if missing:
        print("Samples defined but never used in the docs: " + ", ".join(missing), file=sys.stderr)
    if check and stale:
        print(
            "These generated blocks are out of date:\n  "
            + "\n  ".join(stale)
            + "\n\nRegenerate them with:\n  python scripts/gen_samples.py",
            file=sys.stderr,
        )
    if check:
        return 1 if (stale or missing) else 0
    print(f"Wrote {len(samples.SAMPLES)} sample(s) into {', '.join(TARGETS)}.")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(process(check="--check" in sys.argv))
